import { TaskPhase, TransitionTask } from '../types';

export interface TemplateTaskDefinition {
  templateId: string;
  title: string;
  description: string;
  whyItMatters: string;
  phase: TaskPhase;
  priority: number;
  minEstimatedCost: number;
  maxEstimatedCost: number;
  dependsOnTemplateIds: string[];
  suggestedAssigneeRole?: 'OWNER' | 'FAMILY' | 'LOCAL';
  daysOffsetFromDischarge?: number; // e.g. 0 = discharge day, -4 = 4 days before discharge
}

export const POST_HOSPITAL_WORKFLOW_TEMPLATES: TemplateTaskDefinition[] = [
  {
    templateId: 'confirm-discharge-destination',
    title: 'Confirm safe discharge destination',
    description: 'Verify whether Maria will return directly home with support or spend time in a temporary rehabilitation facility.',
    whyItMatters: 'Maria cannot navigate stairs post-hospitalization. The medical team requires a safe, accessible destination before approving discharge.',
    phase: 'RIGHT_NOW',
    priority: 1,
    minEstimatedCost: 0,
    maxEstimatedCost: 0,
    dependsOnTemplateIds: [],
    suggestedAssigneeRole: 'OWNER',
    daysOffsetFromDischarge: -4,
  },
  {
    templateId: 'assess-accessibility-needs',
    title: 'Assess immediate accessibility needs',
    description: 'Determine required home modifications such as grab bars, ramps, or ground-floor sleeping setup if returning home.',
    whyItMatters: 'Stairs present an immediate safety hazard following a fall. Accessibility modifications must be planned before home entry.',
    phase: 'RIGHT_NOW',
    priority: 2,
    minEstimatedCost: 300,
    maxEstimatedCost: 1200,
    dependsOnTemplateIds: [],
    suggestedAssigneeRole: 'LOCAL',
    daysOffsetFromDischarge: -4,
  },
  {
    templateId: 'decide-temporary-vs-permanent',
    title: 'Decide temporary vs permanent housing',
    description: 'Evaluate whether long-term housing transition is required or if temporary assisted care is the immediate step.',
    whyItMatters: 'Sets the overall transition timeline and determines downstream moving, packing, and financial requirements.',
    phase: 'RIGHT_NOW',
    priority: 3,
    minEstimatedCost: 0,
    maxEstimatedCost: 0,
    dependsOnTemplateIds: ['confirm-discharge-destination'],
    suggestedAssigneeRole: 'OWNER',
    daysOffsetFromDischarge: -3,
  },
  {
    templateId: 'determine-home-return-feasibility',
    title: 'Determine whether returning home is feasible',
    description: 'Review caregiver availability, home layout limitations, and medical recommendations to confirm safety.',
    whyItMatters: 'Avoids premature or unsafe home returns that risk readmission or secondary falls.',
    phase: 'THIS_WEEK',
    priority: 4,
    minEstimatedCost: 0,
    maxEstimatedCost: 0,
    dependsOnTemplateIds: ['assess-accessibility-needs', 'decide-temporary-vs-permanent'],
    suggestedAssigneeRole: 'OWNER',
    daysOffsetFromDischarge: -2,
  },
  {
    templateId: 'inventory-belongings',
    title: 'Inventory belongings',
    description: 'Catalog key furniture, personal heirlooms, and daily necessities to determine packing volume.',
    whyItMatters: 'Essential for getting accurate moving quotes and deciding what fits in the next living space.',
    phase: 'THIS_WEEK',
    priority: 5,
    minEstimatedCost: 0,
    maxEstimatedCost: 0,
    dependsOnTemplateIds: [],
    suggestedAssigneeRole: 'LOCAL',
    daysOffsetFromDischarge: -2,
  },
  {
    templateId: 'shortlist-housing',
    title: 'Shortlist housing options if moving',
    description: 'Filter single-story residences, senior living communities, or accessible apartments in Houston.',
    whyItMatters: 'Ensures Maria moves directly into a safe environment tailored to single-story living.',
    phase: 'THIS_WEEK',
    priority: 6,
    minEstimatedCost: 0,
    maxEstimatedCost: 0,
    dependsOnTemplateIds: ['decide-temporary-vs-permanent'],
    suggestedAssigneeRole: 'OWNER',
    daysOffsetFromDischarge: -1,
  },
  {
    templateId: 'request-moving-estimates',
    title: 'Request moving estimates',
    description: 'Contact senior move managers and specialized local moving services for quotes.',
    whyItMatters: 'Secures reliable professional assistance and sets clear financial expectations.',
    phase: 'THIS_WEEK',
    priority: 7,
    minEstimatedCost: 1200,
    maxEstimatedCost: 2400,
    dependsOnTemplateIds: ['decide-temporary-vs-permanent'],
    suggestedAssigneeRole: 'OWNER',
    daysOffsetFromDischarge: 0,
  },
  {
    templateId: 'decide-belongings-strategy',
    title: 'Decide keep / sell / donate / store strategy',
    description: 'Categorize household items into keep, family inheritances, donation, estate sale, or storage.',
    whyItMatters: 'Reduces moving complexity and costs while preserving meaningful family belongings.',
    phase: 'NEXT',
    priority: 8,
    minEstimatedCost: 300,
    maxEstimatedCost: 700, // donation / junk removal
    dependsOnTemplateIds: ['inventory-belongings'],
    suggestedAssigneeRole: 'LOCAL',
    daysOffsetFromDischarge: 2,
  },
  {
    templateId: 'book-mover',
    title: 'Book mover if needed',
    description: 'Finalize moving service date, scope, packing assistance, and deposit.',
    whyItMatters: 'Locks in moving crew and vehicle availability for the target move date.',
    phase: 'NEXT',
    priority: 9,
    minEstimatedCost: 600,
    maxEstimatedCost: 1100, // packing add-on
    dependsOnTemplateIds: ['request-moving-estimates', 'shortlist-housing'],
    suggestedAssigneeRole: 'OWNER',
    daysOffsetFromDischarge: 4,
  },
  {
    templateId: 'prepare-home',
    title: 'Prepare home for move',
    description: 'Pack essentials, label boxes, clear pathways, and arrange utility transfers.',
    whyItMatters: 'Prevents moving day delays and guarantees essential medical items are accessible.',
    phase: 'MOVE_WEEK',
    priority: 10,
    minEstimatedCost: 250,
    maxEstimatedCost: 450, // cleaning
    dependsOnTemplateIds: ['book-mover'],
    suggestedAssigneeRole: 'LOCAL',
    daysOffsetFromDischarge: 6,
  },
  {
    templateId: 'execute-move',
    title: 'Execute move',
    description: 'Oversee loading, transport, and unloading at the new residence.',
    whyItMatters: 'Ensures Maria’s transition is comfortable, calm, and safe.',
    phase: 'MOVE_WEEK',
    priority: 11,
    minEstimatedCost: 0,
    maxEstimatedCost: 0,
    dependsOnTemplateIds: ['prepare-home', 'book-mover'],
    suggestedAssigneeRole: 'LOCAL',
    daysOffsetFromDischarge: 7,
  },
  {
    templateId: 'final-cleanout',
    title: 'Final cleanout',
    description: 'Complete deep cleaning and final walkthrough of the former home.',
    whyItMatters: 'Prepares home for sale, lease termination, or final handover.',
    phase: 'AFTER_MOVE',
    priority: 12,
    minEstimatedCost: 250,
    maxEstimatedCost: 500,
    dependsOnTemplateIds: ['execute-move'],
    suggestedAssigneeRole: 'LOCAL',
    daysOffsetFromDischarge: 10,
  },
];
