import { Organization, ServiceResource, Location, ResourceVerification } from '../../types';

export interface SeedResourcePackage {
  organization: Organization;
  service: ServiceResource;
  location: Location;
  verification: ResourceVerification;
}

export const HOUSTON_RESOURCE_SEEDS: SeedResourcePackage[] = [
  {
    organization: {
      id: 'org-harris-aaa',
      name: 'Harris County Area Agency on Aging',
      description: 'Official Area Agency on Aging providing family caregiver support, care coordination, and senior housing guidance in Harris County.',
      website: 'https://www.houstontx.gov/health/Aging',
    },
    service: {
      id: 'srv-harris-aaa',
      organizationId: 'org-harris-aaa',
      name: 'Senior Housing Transition & Caregiver Support',
      category: 'senior_move_management',
      description: 'Comprehensive family consultation, case management, and senior living placement assistance.',
      costType: 'free_public_service',
    },
    location: {
      id: 'loc-harris-aaa',
      organizationId: 'org-harris-aaa',
      address: '8000 North Loop East',
      city: 'Houston',
      state: 'TX',
      zipCode: '77029',
      phone: '(832) 393-4301',
    },
    verification: {
      id: 'ver-harris-aaa',
      serviceId: 'srv-harris-aaa',
      verificationStatus: 'Verified public agency',
      verificationSource: 'City of Houston Health Department & Texas HHS',
      lastVerifiedAt: '2026-09-20',
    },
  },
  {
    organization: {
      id: 'org-furniture-bank',
      name: 'Houston Furniture Bank',
      description: '501(c)(3) nonprofit serving Greater Houston families by providing furniture donation pickup and downsizing distribution.',
      website: 'https://houstonfurniturebank.org',
    },
    service: {
      id: 'srv-furniture-bank',
      organizationId: 'org-furniture-bank',
      name: 'Donation Home Pickup & Receipt',
      category: 'donation',
      description: 'Scheduled residential pickup for gently used furniture, beds, and household items with tax receipt.',
      costType: 'donation_pickup',
    },
    location: {
      id: 'loc-furniture-bank',
      organizationId: 'org-furniture-bank',
      address: '8220 Mosley Rd',
      city: 'Houston',
      state: 'TX',
      zipCode: '77075',
      phone: '(713) 842-9771',
    },
    verification: {
      id: 'ver-furniture-bank',
      serviceId: 'srv-furniture-bank',
      verificationStatus: 'Verified 501(c)(3) nonprofit',
      verificationSource: 'IRS Exempt Organizations Database',
      lastVerifiedAt: '2026-09-18',
    },
  },
  {
    organization: {
      id: 'org-rebuilding-together',
      name: 'Rebuilding Together Houston',
      description: 'Nonprofit organization providing home repairs, wheelchair ramps, and safety modifications for low-to-moderate income seniors.',
      website: 'https://rebuildinghouston.org',
    },
    service: {
      id: 'srv-rebuilding-together',
      organizationId: 'org-rebuilding-together',
      name: 'Senior Safety & Home Accessibility Modifications',
      category: 'home_modification',
      description: 'Installation of exterior wheelchair ramps, grab bars, handrails, and fall prevention hazard repairs.',
      costType: 'grant_funded_or_sliding_scale',
    },
    location: {
      id: 'loc-rebuilding-together',
      organizationId: 'org-rebuilding-together',
      address: '4101 San Jacinto St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77004',
      phone: '(713) 659-2511',
    },
    verification: {
      id: 'ver-rebuilding-together',
      serviceId: 'srv-rebuilding-together',
      verificationStatus: 'Verified 501(c)(3) provider',
      verificationSource: 'Rebuilding Together National Registry',
      lastVerifiedAt: '2026-09-22',
    },
  },
  {
    organization: {
      id: 'org-baker-ripley',
      name: 'BakerRipley Senior Services',
      description: 'Community organization operating senior centers, adult day care, and aging-in-place supportive services across Houston.',
      website: 'https://www.bakerripley.org',
    },
    service: {
      id: 'srv-baker-ripley',
      organizationId: 'org-baker-ripley',
      name: 'Adult Day Care & Senior Case Management',
      category: 'senior_move_management',
      description: 'Respite care, community resources, and social work consultation for aging parents.',
      costType: 'sliding_scale',
    },
    location: {
      id: 'loc-baker-ripley',
      organizationId: 'org-baker-ripley',
      address: '4410 Navigation Blvd',
      city: 'Houston',
      state: 'TX',
      zipCode: '77011',
      phone: '(713) 660-5300',
    },
    verification: {
      id: 'ver-baker-ripley',
      serviceId: 'srv-baker-ripley',
      verificationStatus: 'Verified community agency',
      verificationSource: 'United Way Greater Houston Charter',
      lastVerifiedAt: '2026-09-15',
    },
  },
  {
    organization: {
      id: 'org-interfaith',
      name: 'Interfaith Ministries for Greater Houston',
      description: 'Nonprofit managing Meals on Wheels and senior supportive programs across Harris County.',
      website: 'https://www.imgh.org',
    },
    service: {
      id: 'srv-interfaith',
      organizationId: 'org-interfaith',
      name: 'Meals on Wheels & Senior Nutrition Support',
      category: 'senior_move_management',
      description: 'Home-delivered meals and wellness checks for homebound or post-hospital seniors.',
      costType: 'free_public_service',
    },
    location: {
      id: 'loc-interfaith',
      organizationId: 'org-interfaith',
      address: '3303 Main St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77002',
      phone: '(713) 533-4900',
    },
    verification: {
      id: 'ver-interfaith',
      serviceId: 'srv-interfaith',
      verificationStatus: 'Verified 501(c)(3) nonprofit',
      verificationSource: 'Meals on Wheels America Certified Member',
      lastVerifiedAt: '2026-09-19',
    },
  },
  {
    organization: {
      id: 'org-sheltering-arms',
      name: 'Sheltering Arms Senior Services',
      description: 'Specialized senior care agency providing home care coordination, memory care resources, and transition planning.',
      website: 'https://www.shelteringarms.org',
    },
    service: {
      id: 'srv-sheltering-arms',
      organizationId: 'org-sheltering-arms',
      name: 'Post-Hospital In-Home Care Coordination',
      category: 'senior_move_management',
      description: 'Professional care planning, personal care assistance, and transitional safety evaluations.',
      costType: 'hourly_or_quote',
    },
    location: {
      id: 'loc-sheltering-arms',
      organizationId: 'org-sheltering-arms',
      address: '3838 Aberdeen Way',
      city: 'Houston',
      state: 'TX',
      zipCode: '77025',
      phone: '(713) 685-6500',
    },
    verification: {
      id: 'ver-sheltering-arms',
      serviceId: 'srv-sheltering-arms',
      verificationStatus: 'Verified senior provider',
      verificationSource: 'Texas Department of Aging & Disability Services',
      lastVerifiedAt: '2026-09-14',
    },
  },
  {
    organization: {
      id: 'org-metrolift',
      name: 'Houston METROLift Paratransit',
      description: 'Public transit authority paratransit service for persons with mobility limitations unable to use fixed-route buses.',
      website: 'https://www.ridemetro.org',
    },
    service: {
      id: 'srv-metrolift',
      organizationId: 'org-metrolift',
      name: 'Wheelchair-Accessible Medical & Transition Transportation',
      category: 'moving',
      description: 'Shared-ride door-through-door transit for medical visits, housing tours, and appointments.',
      costType: 'public_transit_fare',
    },
    location: {
      id: 'loc-metrolift',
      organizationId: 'org-metrolift',
      address: '1900 Main St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77002',
      phone: '(713) 225-0119',
    },
    verification: {
      id: 'ver-metrolift',
      serviceId: 'srv-metrolift',
      verificationStatus: 'Verified public agency',
      verificationSource: 'Metropolitan Transit Authority of Harris County',
      lastVerifiedAt: '2026-09-24',
    },
  },
  {
    organization: {
      id: 'org-united-way',
      name: 'United Way 211 Texas Greater Houston',
      description: 'Free 24/7 helpline connecting Texas residents to elder care, emergency housing, and food assistance.',
      website: 'https://www.unitedwayhouston.org',
    },
    service: {
      id: 'srv-united-way',
      organizationId: 'org-united-way',
      name: '211 Senior Helpline & Public Assistance Referral',
      category: 'senior_move_management',
      description: 'Immediate navigation to public benefits, Medicaid assistance, and local housing programs.',
      costType: 'free_public_service',
    },
    location: {
      id: 'loc-united-way',
      organizationId: 'org-united-way',
      address: '500 Waverly St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77008',
      phone: '(713) 685-2300',
    },
    verification: {
      id: 'ver-united-way',
      serviceId: 'srv-united-way',
      verificationStatus: 'Verified public helpline',
      verificationSource: 'Texas Information and Referral Network',
      lastVerifiedAt: '2026-09-25',
    },
  },
  {
    organization: {
      id: 'org-lone-star-legal',
      name: 'Lone Star Legal Aid Senior Division',
      description: 'Free civil legal aid for low-income seniors handling housing rights, power of attorney, and estate planning.',
      website: 'https://www.lonestarlegal.org',
    },
    service: {
      id: 'srv-lone-star-legal',
      organizationId: 'org-lone-star-legal',
      name: 'Elder Law & Housing Protection Representation',
      category: 'senior_move_management',
      description: 'Legal consultation on lease terminations, advance directives, and senior housing rights.',
      costType: 'free_legal_aid',
    },
    location: {
      id: 'loc-lone-star-legal',
      organizationId: 'org-lone-star-legal',
      address: '1415 Fannin St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77002',
      phone: '(713) 652-0077',
    },
    verification: {
      id: 'ver-lone-star-legal',
      serviceId: 'srv-lone-star-legal',
      verificationStatus: 'Verified legal aid organization',
      verificationSource: 'Legal Services Corporation (LSC) Grantee',
      lastVerifiedAt: '2026-09-21',
    },
  },
  {
    organization: {
      id: 'org-food-bank',
      name: 'Houston Food Bank Senior Box Program',
      description: 'Supplemental nutrition program providing monthly nutritious food boxes to qualifying seniors age 60+.',
      website: 'https://www.houstonfoodbank.org',
    },
    service: {
      id: 'srv-food-bank',
      organizationId: 'org-food-bank',
      name: 'Commodity Supplemental Food Program (Senior Boxes)',
      category: 'senior_move_management',
      description: 'Monthly home delivery or pickup of shelf-stable groceries for elderly residents.',
      costType: 'free_public_service',
    },
    location: {
      id: 'loc-food-bank',
      organizationId: 'org-food-bank',
      address: '535 Portwall St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77029',
      phone: '(713) 547-8600',
    },
    verification: {
      id: 'ver-food-bank',
      serviceId: 'srv-food-bank',
      verificationStatus: 'Verified 501(c)(3) nonprofit',
      verificationSource: 'Feeding America Member Food Bank',
      lastVerifiedAt: '2026-09-23',
    },
  },
  {
    organization: {
      id: 'org-caregiver-action',
      name: 'Caregiver Action Network Texas',
      description: 'National non-profit organization providing support, education, and peer networks for family caregivers.',
      website: 'https://www.caregiveraction.org',
    },
    service: {
      id: 'srv-caregiver-action',
      organizationId: 'org-caregiver-action',
      name: 'Family Caregiver HelpDesk & Peer Network',
      category: 'senior_move_management',
      description: 'Peer support groups, remote caregiving guides, and transition management checklists for adult children.',
      costType: 'free_public_service',
    },
    location: {
      id: 'loc-caregiver-action',
      organizationId: 'org-caregiver-action',
      address: 'Serving Harris County',
      city: 'Houston',
      state: 'TX',
      zipCode: '77004',
      phone: '(855) 227-3640',
    },
    verification: {
      id: 'ver-caregiver-action',
      serviceId: 'srv-caregiver-action',
      verificationStatus: 'Verified national nonprofit',
      verificationSource: 'National Family Caregivers Association Registry',
      lastVerifiedAt: '2026-09-22',
    },
  },
  {
    organization: {
      id: 'org-texas-hhs-aaa',
      name: 'Texas Health & Human Services Aging Unit',
      description: 'State agency overseeing aging programs, long-term care ombudsman services, and senior benefits.',
      website: 'https://www.hhs.texas.gov',
    },
    service: {
      id: 'srv-texas-hhs-aaa',
      organizationId: 'org-texas-hhs-aaa',
      name: 'Long-Term Care Ombudsman & Benefits Counseling',
      category: 'senior_move_management',
      description: 'Advocacy for residents in long-term care facilities and assistance evaluating senior living options.',
      costType: 'free_public_service',
    },
    location: {
      id: 'loc-texas-hhs-aaa',
      organizationId: 'org-texas-hhs-aaa',
      address: '5425 Polk St',
      city: 'Houston',
      state: 'TX',
      zipCode: '77023',
      phone: '(800) 252-9240',
    },
    verification: {
      id: 'ver-texas-hhs-aaa',
      serviceId: 'srv-texas-hhs-aaa',
      verificationStatus: 'Verified state agency',
      verificationSource: 'Texas Health & Human Services Commission',
      lastVerifiedAt: '2026-09-25',
    },
  },
];
